### ISSUE TITLE
Adding a function to get device from array (type)?

### ISSUE THREAD

**Issue by oschulz** [JuliaGPU/KernelAbstractions.jl#268]
It would be nice to have a function that returns a KernelAbstractions.jl device given an array (type), e.g.

```
get_device(A::AbstractArray) = get_device(typeof(A))

get_device(::Type{<:AbstractArray}) = CPUDevice()
get_device(T::Type{<:AbstractGPUArray}) = throw(ArgumentError("NoKernelAbstractions.Device type defined for arrays of type $(T.name.name)"))

get_device(::Type{<:CuArray}) = CUDADevice()
get_device(::Type{<:AbstractCuSparseArray}) = CUDADevice()

get_device(::Type{<:ROCArray}) = ROCDevice()
```

so that users can write device-agnostic code like

```
function foo(A::AbstractArray)
    A = ones(1024, 1024)
    device = KernelAbstractions.get_device(A)
    kernel = mul2(device, 16)
    event = kernel(A, ndrange=size(A))
    ...
```

Would that fit into the KernelAbstractions concept?

**Comment by oschulz** [comment]
Thanks! Should I do a PR?

**Comment by chriselrod** [comment]
> Ah, no, I don't think that could work, currently: `ArrayInterface.device` is not specific enough, there are no subtypes for different GPU vendors:

I've never really done anything with GPUs / didn't really think about what's actually needed.
That could probably be changed without breaking any actual code. But I also get not wanting to take on a dependency.

**Comment by chriselrod** [comment]
> Bit OT: Why does ArrayInterface have a (comparatively) long load time, actually? For an interface package, I mean?

Discussion: https://github.com/JuliaArrays/ArrayInterface.jl/issues/211#issuecomment-938148292

Personally, I think the library is too big. But a big problem w/ respect to load times is that it uses Requires.jl to add methods for some other libraries. Requires.jl's load times have been improved drastically as of Julia 1.7, so it'll get better.
Because ArrayInterface is using Requires, it could `@requires` KernelAbstractions to define `device` to return `(CUDA/ROC)Device`.
Although
1. What if someone loaded `CUDA` but not `KernelAbstractions` -- what should `ArrayInterface.device` do then?
2. What about CPUs? `ArrayInterface.device` is mostly used currently to say whether or not we can get a `pointer` to it, or if we can get a `pointer` to it after wrapping it in a `Ref`, so the granularity that exists now is needed. Vs the `KernelAbstractions.CPUDevice` used for dispatching without need for granularity.
This means that some coordination would be needed, e.g. defining `AbstractCPUDevice` for `KernelAbstraction` to be able to use for dispatch.

What's the benefit of converging?

**Comment by oschulz** [comment]
> What's the benefit of converging?

I think it would be nice to have a single API to query what kind of device an array lives on, across the ecosystem. I think a truly light-weight package that defines "array traits" would be a good thing to have, long term. Package like CUDA, AMDGPU and oneAPI could than implement those traits together with the array types. And KernelAbstractions (for example) could implement support for those devices types in the vendor-specific kernel packages.

IMHO the occurrence of many `@requires` in the ecosystem is often a sign of a missing lightweight "interface-only" package (like ChainRulesCore) that people are willing to depend on.

Just long-term ramblings ... for now I'll be happy to have `get_device` in KA.
